# Generated by Django 4.1.3 on 2022-12-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('wavelength', models.IntegerField()),
                ('common_name', models.CharField(max_length=255)),
                ('voltaje_register', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
