# Generated by Django 4.1.3 on 2022-12-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_range', models.CharField(blank=True, max_length=255, null=True)),
                ('wavelength', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('common_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='voltaje_register',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='wavelength',
        ),
        migrations.AddField(
            model_name='sensor',
            name='operating_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.IntegerField(choices=[(0, 'Temperatura'), (1, 'ORP'), (2, 'pH'), (3, 'Radiacion'), (4, 'Desconocido')], default=4),
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('voltaje_prom', models.DecimalField(decimal_places=4, max_digits=6)),
                ('max_voltage', models.DecimalField(decimal_places=4, max_digits=6)),
                ('min_voltage', models.DecimalField(decimal_places=4, max_digits=6)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.emisor')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
