# Generated by Django 4.1.3 on 2022-12-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_emisor_remove_sensor_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='operating_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
