# Generated by Django 4.1.3 on 2022-12-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.center'),
        ),
    ]
