# Generated by Django 4.1.3 on 2022-12-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_muestralog'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
